// End-to-end against the guarded local preview and real persisted P7 evidence.
import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
import { mkdirSync, writeFileSync } from 'node:fs';
import path from 'node:path';
const require=createRequire(import.meta.url);
const {chromium}=require(process.env.P7_PLAYWRIGHT || 'playwright');
const output=path.resolve('../research/p5-market-data/p7-ui-check');
mkdirSync(output,{recursive:true});
const browser=await chromium.launch({channel:'msedge',headless:true});
const page=await browser.newPage({viewport:{width:1440,height:1000}});
const errors=[]; page.on('pageerror',e=>errors.push(e.message));
let checks=[];
try {
  await page.goto('http://127.0.0.1:5173/#/tournament');
  await page.locator('input[type=password]').fill('p7-research-preview');
  await page.getByRole('button',{name:'Unlock workspace'}).click();
  await page.waitForFunction(()=>document.querySelectorAll('.arena table tbody tr').length===20);
  assert.equal(await page.locator('.arena table tbody tr').count(),20); checks.push('20 initial strategies');
  const initial=await page.getByTestId('replay-time').textContent();
  await page.getByRole('button',{name:'Play',exact:true}).click();
  await page.waitForFunction(t=>document.querySelector('[data-testid=replay-time]').textContent!==t,initial);
  await page.getByRole('button',{name:'Pause',exact:true}).click();
  const paused=await page.getByTestId('replay-time').textContent();
  await page.waitForTimeout(1300);
  assert.equal(await page.getByTestId('replay-time').textContent(),paused); checks.push('play / pause');
  for(const speed of ['5x','20x','MAX','1x']) {
    await page.getByLabel('Replay speed').selectOption(speed);
    assert.equal(await page.getByLabel('Replay speed').inputValue(),speed);
  }
  checks.push('all speeds');
  await page.getByRole('button',{name:'Restart',exact:true}).click();
  await page.waitForFunction(t=>document.querySelector('[data-testid=replay-time]').textContent===t,initial);
  checks.push('restart');
  await page.getByRole('button',{name:'Final snapshot',exact:true}).click();
  await page.getByRole('heading',{name:'NO_STRATEGY_RESEARCH_QUALIFIED'}).waitFor();
  await page.waitForFunction(()=>document.querySelectorAll('.arena table tbody tr').length===20);
  assert.equal(await page.locator('.arena table tbody tr .REJECTED').count(),1);
  assert.equal(await page.locator('.arena table tbody tr .INSUFFICIENT_EVIDENCE').count(),19);
  assert.ok(await page.locator('.arena-gates .FAIL').count()>0); checks.push('final statuses / zero survivors / gates');
  await page.getByLabel('Family',{exact:true}).selectOption('TREND');
  assert.equal(await page.locator('.arena table tbody tr').count(),8);
  await page.getByLabel('Family',{exact:true}).selectOption('STRUCTURE');
  assert.equal(await page.locator('.arena table tbody tr').count(),0);
  await page.getByLabel('Family',{exact:true}).selectOption('ALL');
  await page.getByLabel('Active / qualified only').check();
  assert.equal(await page.locator('.arena table tbody tr').count(),0);
  assert.equal(await page.locator('.arena-withdrawn button').count(),20);
  await page.getByLabel('Active / qualified only').uncheck(); checks.push('family / survivors filters; failures retained');
  await page.getByRole('button',{name:'MACD crossover TREND',exact:true}).click();
  await page.waitForFunction(()=>document.querySelector('.arena-inspector h2').textContent==='MACD crossover');
  checks.push('strategy selection');
  await page.getByLabel('Timeframe',{exact:true}).selectOption('4H');
  await page.waitForFunction(()=>document.querySelectorAll('.arena table tbody tr .EXCLUDED').length===2);
  await page.getByLabel('Instrument',{exact:true}).selectOption('USOIL');
  await page.waitForFunction(()=>document.querySelector('.arena-inspector>p:nth-of-type(2)')?.textContent.includes('USOIL'));
  await page.getByLabel('Timeframe',{exact:true}).selectOption('1H');
  await page.getByLabel('Instrument',{exact:true}).selectOption('XAGUSD');
  await page.waitForFunction(()=>document.querySelectorAll('.arena table tbody tr .REJECTED').length===1);
  checks.push('instrument / timeframe isolation');
  await page.screenshot({path:path.join(output,'arena-desktop.png'),fullPage:true});
  await page.evaluate(()=>window.scrollTo(0,0));
  await page.screenshot({path:path.join(output,'arena-desktop-viewport.png')});
  assert.ok(await page.locator('.arena-chart polyline').count()>0);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  await page.setViewportSize({width:390,height:844});
  await page.screenshot({path:path.join(output,'arena-mobile.png'),fullPage:true});
  await page.evaluate(()=>window.scrollTo(0,0));
  await page.screenshot({path:path.join(output,'arena-mobile-viewport.png')});
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false);
  checks.push('desktop/mobile chart and overflow');
  assert.deepEqual(errors,[]);
  const report={status:'PASS',checks,consoleErrors:errors,source:'real persisted P7 via guarded read-only preview'};
  writeFileSync(path.join(output,'ui-result.json'),JSON.stringify(report,null,2));
  console.log(JSON.stringify(report));
} finally { await browser.close(); }
