"""Render a bounded raw audit report into the repository evidence note."""
import json
from pathlib import Path
import sys


def main():
    root=Path(__file__).resolve().parents[1]
    path=(root/'research/p5-market-data'/sys.argv[1]).resolve()
    if path.parent != (root/'research/p5-market-data').resolve() or not path.name.startswith('histdata-audit-'):
        raise ValueError('Dedicated audit report required')
    data=json.loads(path.read_text())
    if not all(m['raw_rows']>0 for a in data['instruments'].values() for m in a['months'].values()):
        raise ValueError('Missing source months; do not render a complete-acquisition claim')
    lines=['# P5 HistData-First Audit', '', 'Status: PARTIAL. P6 BLOCKED. Broker execution HARD DISABLED.', '',
           f'Evidence: `{path.name}`. Generated by `scripts/p5_histdata_summary.py`.', '',
           '## Findings', '',
           '- Adjacent disjoint OHLC ranges were over-excluded, although each candle was valid.',
           '  ADR-014 retains them with informational flags; old raw/dataset/qualification versions remain.',
           '- All-month presence below is counted from CSV rows, not inferred from annual filenames.',
           '- No missing month acquisition, paid access, second provider, operator state or broker action.',
           '- Fixed EST UTC-05 remains correct; six DST transition-date regressions pass.',
           '- Complete-only aggregation still rejects bins with absent constituent minutes.',
           '  This includes unproven normal closures and sparse quotes; no partial candle is fabricated.',
           '- No applicable HistData-specific 2021 session calendar was established. Calendar-aware',
           '  weekend/session exemption and trading-session continuous qualification remain NOT PROVEN.',
           '  Missing below includes closures: it is NOT an asserted provider omission rate.',
           '- The existing explicit closure-evidence contract supports documented intervals; no real',
           '  calendar assertions were supplied to it. No numerical gap tolerance was invented.',
           '- Minimum remaining work: establish applicable feed-session/holiday evidence, classify',
           '  closures and residual gaps, then qualify session-aware multi-month ranges. Do not seek',
           '  a second provider merely because complete-bin 24/7 coverage fails.', '',
           'Provider sources: [ASCII specification](https://www.histdata.com/f-a-q/data-files-detailed-specification/)',
           'and [FAQ](https://www.histdata.com/f-a-q/), checked 2026-09-14. They document fixed EST,',
           'bid bars and possible trading pauses, not the exact 2021 calendar needed here.', '',
           '## Raw Acquisition Matrix', '',
           'Months are source fixed-EST months. First/last are unconverted source timestamps.',
           'Monthly bytes are exact CSV row bytes inside one annual archive, not imaginary monthly ZIPs.', '',
           '| Instrument/month | Rows | Parsed | Rejected | Row bytes | First | Last |',
           '|---|---:|---:|---:|---:|---|---|']
    for instrument,a in data['instruments'].items():
        for month,m in a['months'].items():
            lines.append(f'| {instrument}/{month} | {m["raw_rows"]} | {m["accepted_rows"]} | {m["rejected_rows"]} | {m["row_bytes"]} | {m["first_source"]} | {m["last_source"]} |')
    lines+=['','## Archives and Rejections','']
    for instrument,a in data['instruments'].items():
        lines += [f'### {instrument}', '',f'- ZIP bytes: {a["archive_bytes"]}; CSV bytes: {a["csv_bytes"]}; compressed CSV: {a["csv_compressed_bytes"]}.',
                  f'- ZIP SHA256: `{a["archive_sha256"]}`.',
                  f'- Raw/parsed/rejected: {a["raw_rows"]}/{a["accepted_rows"]}/{a["rejected_rows"]}; canonical M1: {a["canonical_M1"]}.',
                  f'- Outside UTC year: {a["outside_UTC_year"]}; unassigned month rows: {a["unassigned_month_rows"]}.',
                  f'- Series classifications: `{json.dumps(a["series_issue_counts"],sort_keys=True)}`.',
                  '- Parse/malformed OHLC/non-finite/timestamp/other rejection counts: '+json.dumps({k:v['reasons'] for k,v in a['months'].items() if v['reasons']})+'.',
                  '- Duplicate timestamps/reasons are retained in the hashed JSON; disputed bars are not guessed.', '']
        print(instrument,a['raw_rows'],a['series_issue_counts'],flush=True)
    lines+=['## Dataset Identity and Qualification','']
    for instrument,a in data['instruments'].items():
        for d in a['datasets']:
            lines += [f'- {instrument} {d["timeframe"]}: `{d["dataset_id"]}`.',
                      f'  Qualification `{d["qualification_id"]}`; {d["state"]}, usable {d["usable_bars"]}, excluded {d["excluded_bars"]}.',
                      f'  Incomplete aggregation bins: {d["incomplete_resample_bins"]}; repeated ingestion/reopen equality PASS.']
    lines+=['','## Annual and Monthly Coverage','',
            'Periods use UTC. Expected is the unexempted grid, NOT verified trading intervals.',
            'Expected closure exemptions: 0. Trading-session contiguous coverage: UNVERIFIED.',
            'Actual bounds and every gap interval are preserved in the hashed JSON and immutable coverage rows.', '',
            '| Instrument/frame/period | Expected grid | Actual | Missing | Missing % | Longest missing seconds | Longest usable bars |',
            '|---|---:|---:|---:|---:|---:|---:|']
    for instrument,a in data['instruments'].items():
        for d in a['datasets']:
            for i,m in enumerate(d['metrics']):
                period='2021 annual' if i==0 else f'2021-{i:02d}'
                lines.append(f'| {instrument}/{d["timeframe"]}/{period} | {m["total_expected_bars"]} | {m["actual_bars"]} | {m["unexplained_missing_bars"]} | {m["unexplained_gap_percentage"]} | {m["longest_unexplained_gap_seconds"]} | {m["longest_usable_segment_bars"]} |')
            m=d['metrics'][0]
            print(instrument,d['timeframe'],d['usable_bars'],m['unexplained_missing_bars'],m['unexplained_gap_percentage'],flush=True)
    lines += ['', '## Verification', '',
              '99 focused / 783 broad tests passed. See TESTING.md for the initial failed legacy',
              'assertion and corrected reruns. Real annual rebuild verified deterministic re-ingestion',
              'and reopen/query equality. Raw observations are real HistData; synthetic prices: NONE.',
              'Session-calendar qualification remains incomplete; P5 is not marked complete.', '']
    (root/'knowledge/Audits/P5-HISTDATA-FIRST.md').write_text('\n'.join(lines),encoding='utf-8',newline='\n')


if __name__=='__main__': main()
